package com.suchasplus.nmea.vo;

import com.suchasplus.nmea.base.AbstractNmeaObject;
import com.suchasplus.nmea.type.Sentence;

/**
 * Powered by suchasplus@gmail.com on 2016/1/18.
 */

/**
 * Waypoint Arrival Alarm Object
 *
 * <link>http://www.gpsinformation.org/dale/nmea.htm#AAM</link>
 *
 * AAM - Waypoint Arrival Alarm is generated by some units to indicate the Status of arrival
 * (entering the arrival circle, or passing the perpendicular of the course line)
 * at the destination waypoint.
 *
 * $GPAAM,A,A,0.10,N,WPTNME*32
 *
 * Where:
 * AAM    Arrival Alarm
 * A      Arrival circle entered
 * A      Perpendicular passed
 * 0.10   Circle radius
 * N      Nautical miles
 * WPTNME Waypoint name
 * *32    Checksum data
 */
public class AamNmeaObject extends AbstractNmeaObject {

    public AamNmeaObject() {
        objType = Sentence.AAM;
    }

    @Override
    public String assemble() {
        return null;
    }
}
